name: Python2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '2.7'
      - name: Install dependencies
        run: pip install coverage pytest alibabacloud-tea-py2
      - name: Test with unittest
        run: cd python2 && coverage run --source="alibabacloud_tea_xml" -m pytest tests/